---
sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "12.0"
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - angelanjimcqueen@gmail.com
      - jkkr.1996@gmail.com
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build #use your build script
deploy:
  provider: s3
  access_key_id: "AKIAIRLJ4HC5L2ROYCMA"
  secret_access_key: "YyMxMUYqRmdajiPYu0acGAK9uuG6G4pJ2/J+g1yX"
  bucket: "cosh-store-app"
  skip_cleanup: true
  on:
    all_branches: true
